### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by kaworu** [bedoherty/MagicTCGPriceAPI#1]
Hi bedoherty,

First of all thanks a lot for this project. With some friends we're playing some Cube drafting with proxies and were wondering how much it would cost to actually get the cards. I wrote a [quick ruby script](https://gist.github.com/kAworu/7108964) to get the price of each card.

Could you consider to put a license to this project please ? As it is, nobody can actually use nor copy it. It is unclear if you want to retain full copyright for this project or if you just did not take the time to pick a license.

Regards & thanks again :)

**Comment by bedoherty** [comment]
My bad man, I intended for this to be fully open.  I'll fix this ASAP.

**Comment by bedoherty** [comment]
Just added an MIT license, hopefully that covers it.  Sorry for an inconvenience.

**Comment by kaworu** [comment]
no problem and thanks for your work !
