### ISSUE TITLE
set name doesn't appear to do anything

### ISSUE THREAD

**Issue by SStrausman** [bedoherty/MagicTCGPriceAPI#10]
That is, when you feed the URI

http://magictcgprices.appspot.com/api/cfb/price.json?cardname=tarmogoyf&setname=modern%masters

you get the same result as 

http://magictcgprices.appspot.com/api/cfb/price.json?cardname=tarmogoyf&setname=future%sight

when there is in fact a 10$ price difference.

**Comment by bedoherty** [comment]
You need to use the parameter "cardset" not "setname" for this API.
