### ISSUE TITLE
Over Quota

### ISSUE THREAD

**Issue by Uthayne** [bedoherty/MagicTCGPriceAPI#2]
I have been noticing that the service stops working most nights around midnight (EST). The server responds with "Over Quota

This application is temporarily over its serving quota. Please try again later." 

Is there too much traffic? Just seems weird that this happens every night around midnight (EST), then is fine again after a few hours.

**Comment by bedoherty** [comment]
I'd guess it's a quota issue with Google App Engine.  You can always try uploading the code to your own instance on Google App Engine if need be.

**Comment by bedoherty** [comment]
I forgot to close this issue, but the problem seems to be that people are making a lot of requests to my free instance of the Google App Engine platform.  If you have problems with this I suggest cloning the project and starting your own free(or paid) instance of App Engine.
