### ISSUE TITLE
Unable to make JSONP request

### ISSUE THREAD

**Issue by Brysonmk1984** [bedoherty/MagicTCGPriceAPI#4]
I receive absolutely nothing in response. Is anyone else having a problem with this? If I go the URL, it works just fine:

http://magictcgprices.appspot.com/api/tcgplayer/price.json?cardname=Congregate&callback=JSON_CALLBACK

Also, should I even be using jsonp or a normal get request?

**Comment by Brysonmk1984** [comment]
Actually, I receive a 404 error. Still clueless on how to get it to work.

**Comment by bedoherty** [comment]
I'd suggest trying a regular GET request.  I've not done any testing with JSONP on this service.
